import Head from 'next/head'
import NavBar from '@/components/NavBar'
import { Col, Container, Row } from 'react-bootstrap'
import Grid from '@/components/grid/Grid'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pathfinder | Hunter Hansen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          <NavBar />
          <Container fluid className="text-center my-2">
            <Row>
              <Col>
                <Grid />
              </Col>
            </Row>
          </Container>
        </>
      </main>
    </>
  )
}
